### ISSUE TITLE
new /permissionsGroups features

### ISSUE THREAD

**Issue by ryran** [ravello/python-sdk#24]
Hey folks. I'm not sure how long it's gonna take for the new permissions stuff to get released .. but it was enabled on our account today and I'm hoping I'll be able to make time this week to play around with it.

Before I go pushing stuff to github, have you already started adding the new user acl stuff in a local branch somewhere? I'll happily let you do all the coding, assuming one of you is already on it (or planning to be on it soon).

**Comment by ryran** [comment]
This is might be a problem with the API .. or it could be a problem with the code I wrote (based on the beta docs I have), but I can't get `del_users_from_permgroup()` to work.

```
>>> a(r.get_users_in_permgroup(1675132)[-1])
{
    "activateTime": "1424204640970", 
    "surname": "User", 
    "name": "PermissionsTest", 
    "roles": [
        "USER"
    ], 
    "activated": true, 
    "enabled": true, 
    "id": 54951950, 
    "_href": "/permissionsGroups/1675132/users/54951950", 
    "invitationTime": "1424203793488", 
    "organization": 49381386, 
    "email": "XXXXXXXXXXXX+ravello@gmail.com", 
    "uuid": "02c96481-55af-4d55-b9dc-d41b3e766a69"
}

>>> r.get_users_in_permgroup(1675132)[-1]['id']
54951950

>>> r.del_user_from_permgroup(1675132, r.get_users_in_permgroup(1675132)[-1]['id'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ravello_sdk.py", line 991, in del_user_from_permgroup
    return self.request('DELETE', '/permissionsGroups/{0}/users'.format(pg), req)
  File "ravello_sdk.py", line 333, in request
    response = self._request(method, path, body, headers)
  File "ravello_sdk.py", line 401, in _request
    raise RavelloError('got status {0} ({1}/{2})' .format(status, code, msg))
ravello_sdk.RavelloError: got status 405 (unknown/unknown)
>>> 
```

I wonder if this is an API thing ... does every user HAVE to be in a permission group? (I guess I'll keep testing.)

**Comment by ryran** [comment]
NEVERMIND. My bad. Fixed.
