### ISSUE TITLE
publish_application() returning HTTP 415

### ISSUE THREAD

**Issue by jonatasbaldin** [ravello/python-sdk#36]
When trying to use publish_application with app parameter and using request() generic method, I got this error:

```python
>>> rav.publish_application(app_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonatas/py_env/ravsys/lib/python3.4/site-packages/ravello_sdk.py", line 549, in publish_application
    self.request('POST', '/applications/{0}/publish'.format(app), req)
  File "/home/jonatas/py_env/ravsys/lib/python3.4/site-packages/ravello_sdk.py", line 346, in request
    response = self._request(method, path, body, headers)
  File "/home/jonatas/py_env/ravsys/lib/python3.4/site-packages/ravello_sdk.py", line 414, in _request
    response.raise_for_status()
  File "/home/jonatas/py_env/ravsys/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 415 Client Error: Unsupported Media Type for url: https://cloud.ravellosystems.com/api/v1/applications/67437297/publish
```

Same on Python 3.4 and 2.7.

**Comment by hadard** [comment]
You should send publish requests details, see: https://www.ravellosystems.com/ravello-api-doc/#publish-application.
I added a default details to the function, see: https://github.com/ravello/python-sdk/commit/cd3d6c8125fc49f675eadddfe3292b6adb110a04
